version: '3.8'

services:
  Grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - app-network

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - app-network
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter
    container_name: nginx-exporter
    ports:
      - "9113:9113"
    networks:
      - app-network
    depends_on:
      - nginx
    command: "--nginx.scrape_uri=http://nginx:8080/status"  # Configure the exporter to scrape metrics
  

  prometheus:
    image: bitnami/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    networks:
      - app-network
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"

networks:
  app-network:
    driver: bridge
