---
- name: Installing Nginx 
  hosts: ubuntu
  tasks:
  - name: Update repo and cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

  - name: Install nginux
    apt:
      name: nginx
      state: latest

- name: Configuring Nginx 
  hosts: ubuntu
  tasks:
  - name: Create ssl directory
    ansible.builtin.file:
      path: /etc/nginx/ssl
      state: directory
  - name: Copy rp.conf 
    ansible.builtin.copy:
       src: /root/ansible/task/rp.conf
       dest: /etc/nginx/conf.d
  - name: copy the certificate
    ansible.builtin.copy:
       src: /root/certs/cert.cer
       dest: /etc/nginx/ssl
  - name: copy the certificate private key
    ansible.builtin.copy:
       src: /root/certs/server.key
       dest: /etc/nginx/ssl
  - name: Start Nginx systemctl
    ansible.builtin.systemd_service:
      state: restarted
      name: nginx
  - name: Reload Nginx
    ansible.builtin.command: nginx -s reload


- name: Configuring Firewall rules and enabling it 
  hosts: ubuntu
  tasks:
  - name: Configuring firewall rules on Ubuntu using ufw to allow 443, 8443 and 22 tcp and enable ufw 
    ansible.builtin.shell: ufw allow 443/tcp ;   ufw allow 8443/tcp ; ufw allow 22/tcp ;
  - name: Enable ufw 
    ansible.builtin.shell: echo "yes" | ufw enable