---
- name: Installing Nginx 
  hosts: ubuntu
  tasks:
  - name: Update repo and cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

  - name: Install nginux
    apt:
      name: nginx
      state: latest

#nginx starts automatically so I don't need to add a task to bring it up

- name: Configuring Nginx 
  hosts: ubuntu
  tasks:
  - name: