---
- name: Configure nginux as a Reverse Proxy, setup a certificate and add firewall rules
  hosts: ubuntu
  tasks:
  - name: Update repo and cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

  - name: Install nginux
    apt:
      name: nginx
      state: latest
